dependencies:
  - name: prometheus
    repository: file://./charts/
    version: "8.15.X"
    condition: global.prometheus.enabled
  - name: grafana
    repository: file://./charts/
    version: "1.X.X"
    condition: global.grafana.enabled
  - name: thanos
    repository: file://./charts/
    version: "0.X.X"
    condition: global.thanos.enabled
