{{- if or .Values.watchers.strimzi .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- if .Values.serviceAccount.nameOverride }}
  name: {{ .Values.serviceAccount.nameOverride }}
  {{- else }}
  name: {{ include "kafka-lag-exporter.fullname" . }}-serviceaccount
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ include "kafka-lag-exporter.name" . }}
    helm.sh/chart: {{ include "kafka-lag-exporter.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}
