apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka-lag-exporter.fullname" . }}-service
  labels:
    app.kubernetes.io/name: {{ include "kafka-lag-exporter.name" . }}
    helm.sh/chart: {{ include "kafka-lag-exporter.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    jobLabel: {{ include "kafka-lag-exporter.fullname" . }}
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "{{ .Values.service.port }}"
    prometheus.io/scrape: "true"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "kafka-lag-exporter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
