apiVersion: v1
kind: Service
metadata:
  name: svc-lb-metabase
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-tcp-idle-timeout: "20"
  namespace: viz
spec:
  type: LoadBalancer
  ports:
  - port: 3333
    targetPort: 3333
  selector:
    app: metabase
