apiVersion: v1
kind: Service
metadata:
  name: svc-lb-yugabyte-ui
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-tcp-idle-timeout: "20"
  namespace: database
spec:
  type: LoadBalancer
  ports:
  - port: 7000
    targetPort: 7000
  selector:
    app: yb-master
