apiVersion: v1
kind: Service
metadata:
  name: svc-lb-schema-registry
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-tcp-idle-timeout: "20"
  namespace: ingestion
spec:
  type: LoadBalancer
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app: cp-schema-registry
