apiVersion: v1
kind: Service
metadata:
  name: svc-lb-kafka-connect
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-tcp-idle-timeout: "20"
  namespace: ingestion
spec:
  type: LoadBalancer
  ports:
  - port: 8083
    targetPort: 8083
  selector:
    app.kubernetes.io/name: kafka-connect
