apiVersion: v1
kind: Service
metadata:
  name: svc-lb-yugabyte-services
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-tcp-idle-timeout: "20"
  namespace: database
spec:
  type: LoadBalancer
  ports:
  - name: tcp-postgres-ysql
    port: 5433
    targetPort: 5433
  - name: tcp-cassandra-yql
    port: 9042
    targetPort: 9042
  - name: tcp-redis-yedis
    port: 6379
    targetPort: 6379
  selector:
    app: yb-tserver
