apiVersion: v1
kind: Service
metadata:
  name: svc-lb-argocd
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-tcp-idle-timeout: "20"
  namespace: cicd
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/name: argocd-server
