apiVersion: v1
kind: Service
metadata:
  name: svc-lb-kubecost
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-tcp-idle-timeout: "20"
  namespace: cost
spec:
  type: LoadBalancer
  ports:
  - port: 9090
    targetPort: 9090
  selector:
    app: cost-analyzer
    app.kubernetes.io/instance: kubecost
